### ISSUE TITLE
liblibtectonic.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by mingrui** [rickyhan/tectonicdb#15]
Hi, I was following the python example code and encountered this error

```
Traceback (most recent call last):
  File "get_order_book.py", line 1, in <module>
    from tectonic import TectonicDB
  File "/mnt/960EVO/workspace/blockchain/myorderbook/tectonic.py", line 5, in <module>
    import ffi
  File "/mnt/960EVO/workspace/blockchain/myorderbook/ffi.py", line 32, in <module>
    lib = CDLL(lib_path)
  File "/home/mingrui/anaconda3/envs/py36_bricks/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /mnt/960EVO/workspace/target/debug/liblibtectonic.so: cannot open shared object file: No such file or directory

```

regarding this line:
https://github.com/rickyhan/tectonicdb/blob/4feaf1028032a3541610295c91073c0cabb3b5dc/cli/python/ffi.py#L31

**Comment by rickyhan** [comment]
You will need to compile first then, change the lib_path variable to where the liblibtectonic.so is.

The other solution is to change this line to

` lib_path = path.normpath('liblibtectonic.so')` and run with

`LD_LIBRARY_PATH=./path/to/lib python run.py`

**Comment by 123mitnik** [comment]
what about when compiling under OSX

building the project doesn't produce any lyb
